### ISSUE TITLE
Can't Run

### ISSUE THREAD

**Issue by jelmani** [cisc3620/2-draw-triangle#2]
@rivlev 

After building with cmake, my directory looks like this:

![graphicsdirectory](https://cloud.githubusercontent.com/assets/14169947/22806865/346a8d64-eef2-11e6-9936-67e5ffed494f.png)

Whenever I open any of those project files in visual studio and run them I get an error message:

![vserror](https://cloud.githubusercontent.com/assets/14169947/22806985/c2c83d5e-eef2-11e6-874c-837723a35edf.png)

It seems Visual Studio is trying to run an executable that isn't there. Is there something I'm missing? I'm not sure what to do next, any help would be really appreciated

**Comment by rivlev** [comment]
There are three steps here
* generate project files with cmake
   ```cmake -G "Visual Studio" ..```
* build (with cmake or in your ide)
   ```cmake --build .```
* run the executable. The executable will be in Build/Glitter/Debug/ and called Glitter. You can double click it from your file explorer or run it from the command line.

**Comment by rivlev** [comment]
+1 for issue

**Comment by jelmani** [comment]
@rivlev 
Thank you. Now when I click the executable it says: "Failed to create OpenGL context"

**Comment by TarekCodes** [comment]
@jelmani I had a similar issue and I fixed it by right clicking "Glitter" in the Solution Explorer and setting it as startup project. After that I rebuilt and ran it again and it worked all through Visual Studio.

**Comment by jelmani** [comment]
I can run it through Visual Studio now, but I'm still getting the Failed to create OpenGL context. Thank you @TS96

**Comment by rivlev** [comment]
That probably means your graphics card doesn't support the version of OpenGl you have specified in your initial glfwWindowHints
Check what version your graphics card supports, update drivers if possible
Then modify the glfwWindowHints to be e.g. Major 3 and Minor 3 instead of Major 4 and Minor 0

**Comment by jelmani** [comment]
I changed the glfwWindowHints values around to different values and I still got the Failed to create error. I downloaded a program called OpenGL extensions viewer that checks what version of OpenGL my graphics card can support and it says 3.1 so I'm not sure what the problem is

**Comment by jelmani** [comment]
I got it to run! I just commented out the line that specifies the profile as Core Profile. Apparently that profile disallows the use of deprecated features. Closing issue, thank you!

**Comment by rivlev** [comment]
Glad it's working, but there shouldn't be any deprecated features in there

Make sure that you are using modern opengl (with shaders)

**Comment by jelmani** [comment]
@rivlev 

Should the triangle be white initially? Also I'm seeing I'm unable to change the color of the triangle by changing the values in the fragmentShaderSource variable. Would this mean I'm not using modern opengl?

**Comment by rivlev** [comment]
The triangle should be orange initially

If you are using shaders, that's modern opengl. I'm not sure what you mean by the values in fragment shader source. You should store the colors along with the coordinates and pass them all to the shaders; the shaders should just pass them through. See the learnopengl tutorial.

**Comment by jelmani** [comment]
@rivlev 

So I believe my graphics card was just too old. I tried on my sister's computer and it worked perfectly.

**Comment by rivlev** [comment]
Closing
